name: Chess AI Tests

on:
  push:
    branches: [ main ]  # Run tests on pushes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
    - uses: actions/checkout@v2  # Check out your repository code
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Replace with your Python version (e.g., '3.8')
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Install dependencies from your requirements.txt
    - name: Run tests
      run: python test_script.py  # Execute your test script